[project]
name = 'v2'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'SP3DX3H4FEYZJZ586MFBS25ZW3HZDMEW92260R2PR.Wrapped-Bitcoin'
[contracts.clarity-bitcoin]
path = 'contracts/_v1-clarity-bitcoin.clar'
clarity_version = 2
epoch = 2.1

[contracts.clarity-bitcoin-v2]
path = 'contracts/clarity-bitcoin-v2.clar'
clarity_version = 2
epoch = 2.1

[contracts.test-utils]
path = 'contracts/test/test-utils.clar'
clarity_version = 2
epoch = 2.1

[contracts.magic]
path = 'contracts/magic.clar'
clarity_version = 2
epoch = 2.1
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
