[project]
name = 'v2'
description = ''
authors = []
telemetry = false
cache_dir = './.cache'
requirements = []
[contracts.clarity-bitcoin-v2]
path = 'contracts/clarity-bitcoin-v2.clar'
clarity_version = 1
epoch = 2.0
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
